export const TOOLS_DIR = "./tools/";

export const supportedZXTuneFormats = new Set<string>([
  "ASC",
  "FTC",
  "GTR",
  "PSC",
  "PSG",
  "PSM",
  "PT1",
  "PT2",
  "PT3",
  "SQT",
  "STC",
  "ST1",
  "ST3",
  "STP",
  "VTX",
  "AY",
  "YM",
  "CHI",
  "DMM",
  "DST",
  "ET1",
  "PDT",
  "SQD",
  "STR",
  "TFC",
  "TFD",
  "TFE",
  "669",
  "AMF",
  "DMF",
  "FAR",
  "FNK",
  "GDM",
  "IMF",
  "IT",
  "LIQ",
  "MDL",
  "MPTM",
  "MTM",
  "PTM",
  "RTM",
  "S3M",
  "STIM",
  "STM",
  "STX",
  "ULT",
  "XM",
  "DBM",
  "EMOD",
  "MOD",
  "MTN",
  "IMS",
  "MED",
  "OKT",
  "PT36",
  "SFX",
  "AHX",
  "DTM",
  "GTK",
  "TCB",
  "SAP",
  "DTT",
  "COP",
  "SID",
  "AYC",
  "SPC",
  "MTC",
  "VGM",
  "GYM",
  "NSF",
  "NSFe",
  "GBS",
  "GSF",
  "HES",
  "KSS",
]);

export const supportedFurnaceFormats = new Set<string>(["FUR"]);
export const supportedChipnsfxFormats = new Set<string>(["CHP"]);
export const supportedPSGplayFormats = new Set<string>(["SNDH", "SND"]);
export const supportedArkosFormats = new Set<string>(["AKS", "128", "SKS", "WYZ"]);

export const commonAYMChipFrequencies: Array<[string, string]> = [
  ["zx", "1773400"],
  ["pentagon", "1750000"],
  ["bk", "1710000"],
  ["vectrex", "1500000"],
  ["cpc", "1000000"],
  ["oric", "1000000"],
  ["st", "2000000"],
  ["taganrog", "3000000"],
  ["ql", "750000"],
];

export const commonAYMLayouts = ["abc", "acb", "bac", "bca", "cba", "cab", "mono"] as const;
